### PR TITLE
Remove top level packages directory

### PR DESCRIPTION
**Pull request by MichaelSimons**
Related to https://github.com/dotnet/source-build/issues/2867

The top level packages directory was "moved" into the prereqs folder with https://github.com/dotnet/installer/pull/15140.  This PR is needed to remove the top level directory.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
This is blocked on https://github.com/dotnet/installer/pull/15144#issuecomment-1355554383.

**Comment by premun** [comment]
@MichaelSimons I will take care of this. I guess I missed refs/head/main in the branch filter?

**Comment by MichaelSimons** [comment]
> @MichaelSimons I will take care of this. I guess I missed refs/head/main in the branch filter?

I suspect that's what the issue is.

**Comment by premun** [comment]
Just for the record, the problem was that the parameter's default value is `$(Build.SourceBranchName)` so `parameters.vmrBranch` turns into `$(Build.SourceBranchName)` which doesn't get evaluated in `${{ if }}`. But now I have tried and it doesn't get evaled in a `condition` neither..

**Review by premun — APPROVED** [review]

**Pull request merged**
