### PR TITLE
Remove cloaked licenses from vstest

### PR DESCRIPTION
**Pull request by premun**
Files were cloaked in https://github.com/dotnet/installer/commit/ffb1fa4dde21b3b5d6bb5c93d57df52a68c0440c

Fixes https://github.com/dotnet/source-build/issues/3538 and https://github.com/microsoft/vstest/issues/4574

### CODE REVIEW

**Comment by premun** [comment]
These should have been caught by the cloaked file scanner though.. :-/

I will log an issue for this

**Review by MichaelSimons — APPROVED** [review]

**Comment by mthalman** [comment]
@premun - This is causing a build failure in vstest:

```
/vmr/.dotnet/sdk/8.0.100-preview.6.23330.14/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error : Could not find a part of the path '/vmr/src/vstest/artifacts/source-build/self/src/src/package/licenses'. [/vmr/src/vstest/artifacts/source-build/self/src/src/Microsoft.TestPlatform.Build/Microsoft.TestPlatform.Build.csproj]
```

**Comment by MichaelSimons** [comment]
@premun - It looks like the original PR validation caught this.  Why were the changes merged before PR validation completed?

**Comment by premun** [comment]
@MichaelSimons seems like the `dotnet-dotnet` check was not set as required and auto-complete just merged this. I will fix the setting in GitHub

**Pull request merged**
