### PR TITLE
Delete cloaked winforms test

### PR DESCRIPTION
**Pull request by ellahathaway**
Deletes the winforms test that was cloaked in https://github.com/dotnet/installer/pull/19218

### CODE REVIEW

**Comment by ellahathaway** [comment]
cc @dotnet/source-build-internal

**Review by mthalman — APPROVED** [review]

**Comment by ellahathaway** [comment]
@mthalman - I don't have write access for this repo, could you merge this for me please?

**Comment by mthalman** [comment]
The deletion of this project is causing the Windows vertical build to fail. That will need to be resolved.

**Comment by ellahathaway** [comment]
Waiting on the changes from https://github.com/dotnet/winforms/pull/11140 to flow in to the VMR. After that, I'll update this PR to readd the two project files. I'll also update the source-mappings.json in another PR to allow the two project files back into the VMR.

**Comment by ellahathaway** [comment]
The VMR did not sync the two project files due to the cloaking.

I updated the source-mappings.json in https://github.com/dotnet/installer/pull/19282. I then locally reinitialized winforms in the VMR using `dotnet darc vmr initialize --vmr /root/repos/dotnet2/ --source-mappings /root/repos/installer/src/VirtualMonoRepo/source-mappings.json winforms:50add59bd0407dc3e1b5003ec56f592f06c32bda`. The result of that is what you see in this PR.

**Review by mthalman — APPROVED** [review]

**Comment by ellahathaway** [comment]
@dotnet/source-build-internal - Soft ping. Could someone with permissions merge this when they get a chance? Thanks!

**Pull request merged**
