### PR TITLE
Remove NuGet configs of several submodules

### PR DESCRIPTION
**Pull request by premun**
https://github.com/dotnet/installer/pull/16386
https://github.com/dotnet/source-build/issues/3152
https://github.com/dotnet/source-build/issues/3230

### CODE REVIEW

**Comment by premun** [comment]
@MichaelSimons this one is needed as well

**Comment by MichaelSimons** [comment]
I see this auto-merged.  Isn't that a potential issue given https://github.com/dotnet/installer/pull/16386 is not yet merged?  If another installer PR is merged before https://github.com/dotnet/installer/pull/16386 is merged then the NuGet.configs will get mirrored again.

**Comment by premun** [comment]
Only problem could happen if there was a change to one of the `NuGet.config` files in between that. And I don't think that's likely.

**Comment by premun** [comment]
As in, we'd have to merge a change from SB externals that would also be changing a submodule that just changed a config

**Pull request merged**
