### PR TITLE
[sdk] Sync be2654e → 636ba11 (Test moving dotnet/format to dotnet/sdk)

### PR DESCRIPTION
**Pull request by Cosifne**
Diff: https://github.com/dotnet/sdk/compare/be2654e7f453bf795bd9a73965fd4e76435bc170..636ba11b107f5a32207f4c920a202021f8d2bb00

From: https://github.com/dotnet/sdk/commit/be2654e7f453bf795bd9a73965fd4e76435bc170
To: https://github.com/dotnet/sdk/commit/636ba11b107f5a32207f4c920a202021f8d2bb00

[[ commit created by automation ]]

This is to validate moving dotnet/format to dotnet/sdk

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@Cosifne - In case you didn't see, the conflicts need to be resolved to CI to run.

**Comment by Cosifne** [comment]
> @Cosifne - In case you didn't see, the conflicts need to be resolved to CI to run.

Seems like the repo is updated frequenetly... let me regenerate this

**Comment by MichaelSimons** [comment]
@Cosifne - I think one change is needed to disable building the old dotnet/format repo.  This line needs to be commented out - https://github.com/dotnet/dotnet/blob/main/repo-projects/sdk.proj#L21

**Comment by MichaelSimons** [comment]
It won't be a valid test without this.

**Comment by MichaelSimons** [comment]
The actual build succeeded but there were detected prebuilts so it failed at the end.  I investigated the prebuilts and they look to be caused by the way we only sync'd the sdk repo.  I pushed a change to ignore prebuilts because I would like the tests to run.

**Comment by MichaelSimons** [comment]
@Cosifne - there was one issue caught by the tests.  The test is ensuring all native files include symbols.  This is the test logic.  https://github.com/dotnet/dotnet/blob/main/test/Microsoft.DotNet.SourceBuild.SmokeTests/DebugTests.cs

```
missing .debug_info section in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
missing .debug_abbrev section in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
missing FILE symbols in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
```

**Comment by Cosifne** [comment]
> @Cosifne - there was one issue caught by the tests. The test is ensuring all native files include symbols. This is the test logic. https://github.com/dotnet/dotnet/blob/main/test/Microsoft.DotNet.SourceBuild.SmokeTests/DebugTests.cs
> 
> ```
> missing .debug_info section in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
> missing .debug_abbrev section in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
> missing FILE symbols in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net9.0/.dotnet/sdk/9.0.100-preview.3.24164.1/dotnet-format
> ```

I checked the test, looks like it is just enumerated all the files under sdk/{version}/ and check if symbol file exists.
The problem I think is a deployment issue. I feel the correct location should be sdk/{version}/Dotnettools/dotnet-format so these file should not be checked by the test. Also dotnet-format is all written in C#.

**Comment by MichaelSimons** [comment]
> I feel the correct location should be sdk/{version}/Dotnettools/dotnet-format so these file should not be checked by the test.

The test is responsible for validating all files that are included with the SDK.  The test is extracting the just build SDK and scanning it.  

When I look at the built SDK, I am seeing several dotnet-format files under sdk/{version}.  Why are these here, I don't see similar files for the other tools (e.g. dotnet watch).  Additionally, I don't see these in an SDK build prior to the format merge.  The build artifacts contain the built SDK if you want to look - https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzYwMzQ1MS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfTXNmdFNka194NjRfQXJ0aWZhY3Rz0/content?format=file&subPath=%2Fdotnet-sdk-9.0.100-preview.3.24164.1-centos.8-x64.tar.gz

**Comment by Cosifne** [comment]
> > I feel the correct location should be sdk/{version}/Dotnettools/dotnet-format so these file should not be checked by the test.
> 
> The test is responsible for validating all files that are included with the SDK. The test is extracting the just build SDK and scanning it.
> 
> When I look at the built SDK, I am seeing several dotnet-format files under sdk/{version}. Why are these here, I don't see similar files for the other tools (e.g. dotnet watch). Additionally, I don't see these in an SDK build prior to the format merge. The build artifacts contain the built SDK if you want to look - https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzYwMzQ1MS9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOF9PbmxpbmVfTXNmdFNka194NjRfQXJ0aWZhY3Rz0/content?format=file&subPath=%2Fdotnet-sdk-9.0.100-preview.3.24164.1-centos.8-x64.tar.gz

Found the problem, fixing now

**Comment by MichaelSimons** [comment]
A green source-build 🎉!

**Comment by MichaelSimons** [comment]
@Cosifne - feel free to close this PR if/once you are done testing.

**Pull request closed without merging**
